apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-deployment
spec:
  selector:
    matchLabels:
      app: demo-api
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: gitlab:5000/k8s-demo-api:latest
        ports:
        - containerPort: 8080
          name: server
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
